/****************************
*  
*  Common views
*  
*  forms for:
*    - showFormAddNews
*    - showFormEditNews
*
****************************/
var view = {
	showFormAddNews: function () {
		$("#form_add_news").remove();
		$("#content .next_news").remove();
		$("#content .article_add_news").remove();
		$("#content").append(''
		 + '<article class="article_add_news">'
     + '<header class="title">'
     + '           <h3>Add News</h3>'
     + '    </header>'
      + ' <div class="article_content"> '
      + '           <form id="form_add_news"> '
      + '          <fieldset> '
      + '                       '
      + '                      <ol> '
      + '                          <li> '
      + '                              <label for="author">Name</label> '
      + '                              <input type="text" id="author" name="author" pattern=".{4,}" placeholder="Your name" required /> '
      + '                              <p class="validation01"> '
      + '                                  <span class="invalid">At least 4 characters</span> '
      + '                                  <span class="valid">nice to meet you</span> '
      + '                              </p> '
      + '                          </li> '
      + '                          <li> '
      + '                              <label for="title">Title</label> '
      + '                              <input type="text" id="title" name="title" pattern=".{6,}" placeholder="News title" required /> '
      + '                              <p class="validation01"> '
      + '                                  <span class="invalid">At least 6 characters</span> '
      + '                                  <span class="valid">cool ;)</span> '
      + '                              </p> '
      + '                          </li> '
      + '                          <li> '
      + '                                              <label for="cat_id">Category</label> '
      + '                                              <select name="cat_id" id="cat_id"> '
      + '                                              		<option selected>Other</option> '
      + '                                                  <option>HTML</option> '
      + '                                                  <option>CSS</option> '
      + '                                                  <option>JavaScript</option> '
      + '                                                  <option>Ruby</option> '
      + '                                              </select> '
      + '                                          </li> '
      + '                          <li> '
      + '                              <label for="tags">Tags</label> '
      + '                              <input type="text" id="tags" name="tags" placeholder="e.g. html, css" required /> '
      + '                              <p class="validation01"> '
      + '                                  <span class="invalid">Separator: ","</span> '
      + '                                  <span class="valid">nice :)</span> '
      + '                              </p> '
      + '                          </li> '
			+ '														<li> '
      + '                              <label for="news_content">Content</label> '
      + '                              <textarea id="news_content" name="content" placeholder="Your news" rows="10" required ></textarea> '
      + '                               <p class="validation01"> '
      + '                                  <span class="invalid">Type your news</span> '
      + '                                  <span class="valid">mmm.. interesting</span> '
      + '                              </p> '
      + '                          </li> '
      + '                      </ol> '
      + '                  </fieldset> '
			+ '								<!-- <input type="submit" value="add" /> --> '
      + '             </form> '
      + '      </div> '
			+ '			<span class="add_it" onclick="modelNews.addNews();">add</span>'
			+ '</article>'
				).hide().animate({ opacity: "show" }, "slow");
		},
  showFormEditNews: function (news) {
		$("#form_edit_news").remove();
    $("article").hide();
    $("#content .next_news").remove();
		$("#content").append(''
		 + '<article class="article_edit_news">'
     + '<header class="title">'
     + '           <h3>Edit News</h3>'
     + '    </header>'
      + ' <div class="article_content"> '
      + '           <form id="form_edit_news"> '
      + '          <fieldset> '
      + '                       '
      + '                      <ol> '
      + '                          <li> '
      + '                              <label for="author">Name</label> '
      + '                              <input type="text" id="author" name="author" pattern=".{4,}" value="' + news.author + '"  required /> '
      + '                              <p class="validation01"> '
      + '                                  <span class="invalid">At least 4 characters</span> '
      + '                                  <span class="valid">nice to meet you</span> '
      + '                              </p> '
      + '                          </li> '
      + '                          <li> '
      + '                              <label for="title">Title</label> '
      + '                              <input type="text" id="title" name="title" pattern=".{6,}"  value="' + news.title + '"  required /> '
      + '                              <p class="validation01"> '
      + '                                  <span class="invalid">At least 6 characters</span> '
      + '                                  <span class="valid">cool ;)</span> '
      + '                              </p> '
      + '                          </li> '
      + '                          <li> '
      + '                                              <label for="cat_id">Category</label> '
      + '                                              <select name="cat_id" id="cat_id"> '
      + '                                              		<option selected>Other</option> '
      + '                                                  <option>HTML</option> '
      + '                                                  <option>CSS</option> '
      + '                                                  <option>JavaScript</option> '
      + '                                                  <option>Ruby</option> '
      + '                                              </select> '
      + '                                          </li> '
      + '                          <li> '
      + '                              <label for="tags">Tags</label> '
      + '                              <input type="text" id="tags" name="tags" value="' + news.tags + '" required /> '
      + '                              <p class="validation01"> '
      + '                                  <span class="invalid">Separator: ","</span> '
      + '                                  <span class="valid">nice :)</span> '
      + '                              </p> '
      + '                          </li> '
			+ '														<li> '
      + '                              <label for="news_content">Content</label> '
      + '                              <textarea id="news_content" name="content" rows="10" required >' + news.content + '</textarea> '
      + '                               <p class="validation01"> '
      + '                                  <span class="invalid">Type your news</span> '
      + '                                  <span class="valid">mmm.. interesting</span> '
      + '                              </p> '
      + '                          </li> '
      + '                      </ol> '
      + '                  </fieldset> '
			+ '								<!-- <input type="submit" value="add" /> --> '
      + '             </form> '
      + '      </div> '
			+ '			<span class="edit_news" onclick="modelNews.updateNews(\'' + news.id + '\');">edit</span>'
			+ '</article>'
				);
	}
}

